version: '3.7'
volumes:
  postgres_data:
  static_data:
  media_data:
services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    image: h0diush/yamdb_final:latest
    restart: always
    depends_on:
      - db
    volumes:
      - static_data:/var/html/static/
      - media_data:/var/html/media/
  nginx:
    image: nginx:1.19.0
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_data:/var/html/static/
      - media_data:/var/html/media/